🎯 Learning Objectives
Learn why NumPy is important in AI/ML.
Work with arrays and mathematical operations.

📺 YouTube Search
NumPy Tutorial for Beginners
NumPy Arrays
NumPy Indexing
NumPy Mathematical Operations

🔗 Recommended Channels
Krish Naik
CampusX
Codebasics
📖 Documentation (Relevant)
NumPy Official Documentation (Getting Started)

💻 Tasks

-Install NumPy.
-Create 1D and 2D arrays.
-Practice indexing and slicing.
-Perform mathematical operations (sum, mean, max, min).
-Compare Python Lists with NumPy Arrays.
Create a small Student Marks Analysis using NumPy.
Push your work to GitHub.

📂 Deliverables
✅ NumPy practice notebook
✅ Student Marks Analysis
✅ GitHub updated

NumPy (Numerical Python) is a Python library used for numerical computing. It provides fast, efficient multi-dimensional arrays and mathematical operations, making it one of the fundamental libraries used in Data Science, AI, and Machine Learning.

Why NumPy is important in AI/ML-

- Handles large numerical datasets efficiently
- Provides fast array operations
- Supports mathematical and statistical calculations
- Forms the foundation for libraries like Pandas, Scikit-learn and SciPy
- Makes matrix and vector operations easier
- Uses optimized operations that are generally faster than Python loops

In [1]:
import numpy as np

# 1D Array
marks = np.array([85, 72, 90, 65, 78])

# 2D Array
data = np.array([
    [85, 72, 90],
    [65, 78, 88]
])

print(marks)
print(data)

[85 72 90 65 78]
[[85 72 90]
 [65 78 88]]


In [2]:
print(marks[0])       # First element
print(marks[-1])      # Last element
print(marks[1:4])     # Slicing

85
78
[72 90 65]


In [4]:
print(np.sum(marks))
print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))

390
78.0
90
65


In [3]:
print(marks + 5)
print(marks * 2)
print(np.sqrt(marks))

[90 77 95 70 83]
[170 144 180 130 156]
[9.21954446 8.48528137 9.48683298 8.06225775 8.83176087]


In [5]:
#Student Marks Analysis
marks = np.array([78, 85, 92, 67, 88, 74, 95, 81, 69, 90])

print("Marks:", marks)
print("Total Marks:", np.sum(marks))
print("Average Marks:", np.mean(marks))
print("Highest Marks:", np.max(marks))
print("Lowest Marks:", np.min(marks))
print("Above Average:", marks[marks > np.mean(marks)])

Marks: [78 85 92 67 88 74 95 81 69 90]
Total Marks: 819
Average Marks: 81.9
Highest Marks: 95
Lowest Marks: 67
Above Average: [85 92 88 95 90]


| Python List | NumPy Array |
|---|---|
| General-purpose collection | Designed for numerical computing |
| Can contain different data types | Usually contains same data type |
| Mathematical operations require loops | Supports vectorized operations |
| Generally slower for numerical operations | Faster for numerical operations |
| Less suitable for matrix operations | Excellent for matrix/vector operations |

In [6]:
# Python List
marks = [10, 20, 30]
print([x * 2 for x in marks])

# NumPy Array
marks_np = np.array([10, 20, 30])
print(marks_np * 2)

[20, 40, 60]
[20 40 60]
